#!/bin/sh

CONF_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/node-red
WWW_DIR=/usr/local/etc/config/addons/www/redmatic

NODE=$ADDON_DIR/bin/node

export PATH=$ADDON_DIR/bin:$PATH
export NO_UPDATE_NOTIFIER=true

RED_DIR=$ADDON_DIR/lib/node_modules/node-red
RED=$RED_DIR/red.js

SETTINGS=$ADDON_DIR/settings.js

Stop () {
    PSPID=`ps -o pid,comm,args | awk '{if($3 == "node-red" || $4 ~ /node-red/){print $1}}'`
    if [ "$PSPID" != "" ]
    then
      echo -n "Stopping Node-RED: "
      kill $1 $PSPID 2>/dev/null
      sleep 1
      kill -0 $PSPID 2>/dev/null
      if [ $? -eq 0 ]
      then
        sleep 10
        kill -KILL $PSPID 2>/dev/null
      fi
      logger -t homematic -p user.info "stopped node-red"
      echo "OK"
    fi
}

Start () {
    echo -n "Starting Node-RED: "
    $NODE $RED -s $SETTINGS 2>&1 | logger -p user.info -t node-red &
    logger -t homematic -p user.info "started node-red"
    echo "OK"
}

case "$1" in

  stop)
    Stop
  ;;

  start)
    Start
  ;;

  restart)
    Stop
    sleep 1
    Start
  ;;

  info)
    source $ADDON_DIR/versions
    echo "Info: <a href="https://github.com/hobbyquaker/RedMatic"><img src="/addons/redmatic/logo-w-200.png" align="right"/></a>"
    echo "Info: <table><tr><td>Node.js</td><td>$NODE_VERSION</td></tr>"
    echo "Info: <tr><td>npm</td><td>$VERSION_npm</td></tr>"
    echo "Info: <tr><td>Node-RED</td><td>$VERSION_nodered</td></tr>"
    echo "Info: <tr><td>Node-RED Dashboard</td><td>$VERSION_nodereddashboard</td></tr>"
    echo "Info: <tr><td>node-red-contrib-ccu</td><td>$VERSION_noderedcontribccu</td></tr></table>"
    echo "Name: RedMatic"
    echo "Version: $VERSION_ADDON"
    echo "Update: /addons/redmatic/update_check.cgi"
    echo "Operations: restart uninstall"
  ;;

  uninstall)
     Stop
     $ADDON_DIR/update_addon node-red
     $ADDON_DIR/update_addon node-red-dashboard
     rm -r $ADDON_DIR
     rm -r $WWW_DIR
     rm $CONF_DIR/addons/www/check_update_node_red.cgi
     rm $CONF_DIR/lighttpd/node-red.conf
     rm $CONF_DIR/rc.d/node-red
  ;;

  *)
    echo "Usage: node-red {start|stop|restart|info|uninstall}" >&2
    exit 1
  ;;

esac



exit 0