#!/bin/sh

ADDONS_DIR=/usr/local/addons
RED_DIR=$ADDONS_DIR/redmatic
CONF_DIR=/usr/local/etc/config
WWW_DIR=$CONF_DIR/addons/www/redmatic

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

mkdir -p $ADDONS_DIR && chmod 755 $ADDONS_DIR 
mkdir -p $WWW_DIR && chmod 755 $WWW_DIR

if [ -f $CONF_DIR/rc.d/redmatic ]; then
    $CONF_DIR/rc.d/redmatic stop
fi

if [ -f $RED_DIR/settings.js ]; then
    cp $RED_DIR/settings.js $RED_DIR/settings.js.old
fi

cp -af redmatic $ADDONS_DIR/


# migration
if [ -d $ADDONS_DIR/node-red ]; then

    if [ -f $CONF_DIR/rc.d/node-red ]; then
        $CONF_DIR/rc.d/node-red stop
    fi
    if [ -f $CONF_DIR/addons/www/check_update_node_red.cgi ]; then
        rm $CONF_DIR/addons/www/check_update_node_red.cgi
    fi
    if [ -f $CONF_DIR/lighttpd/node-red.conf ]; then
        rm $CONF_DIR/lighttpd/node-red.conf
    fi

    cp $ADDONS_DIR/node-red/var/flows.json $RED_DIR/var/flows.json
    cp $ADDONS_DIR/node-red/settings.js $RED_DIR/var/settings.js.old

    rm -rf $ADDONS_DIR/node-red
fi


mkdir -p $CONF_DIR/lighttpd
ln -sf $RED_DIR/lighttpd.conf $CONF_DIR/lighttpd/redmatic.conf


chmod a+x $RED_DIR/node-red
ln -sf $RED_DIR/redmatic $CONF_DIR/rc.d/redmatic

if [ ! -f $RED_DIR/var/flows.json ]; then
    mv $RED_DIR/var/example-flows.json $RED_DIR/var/flows.json
fi

ln -s $RED_DIR/update_check.tcl $WWW_DIR/update_check.cgi
ln -s $RED_DIR/logo-w-200.png $WWW_DIR/logo-w-200.png

touch $CONF_DIR/hm_addons.cfg

./update_addon node-red node-red.cfg
./update_addon node-red-dashboard node-red-dashboard.cfg

sync

exit 0
