#!/bin/sh

ADDONS_DIR=/usr/local/addons
RED_DIR=$ADDONS_DIR/redmatic
CONF_DIR=/usr/local/etc/config
WWW_DIR=$CONF_DIR/addons/www/redmatic
EXITCODE=10

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

mkdir -p $ADDONS_DIR && chmod 755 $ADDONS_DIR 
mkdir -p $WWW_DIR && chmod 755 $WWW_DIR
mkdir -p $CONF_DIR/lighttpd && chmod 755 $CONF_DIR/lighttpd

#
#   Stop service on update
#
if [ -f $CONF_DIR/rc.d/redmatic ]; then
    EXITCODE=0
    $CONF_DIR/rc.d/redmatic stop
fi

#
#   Rename extra nodes package.json on update
#
if [ -f $RED_DIR/var/package.json ]; then
    mv $RED_DIR/var/package.json $RED_DIR/var/package.json.old
fi

#
#   Delete included modules from lib/node_modules on update.
#   The lib layer is fully owned by the addon (palette installs live in var),
#   so stale modules from previous versions must not survive an update.
#
if [ -d $RED_DIR/lib/node_modules ]; then
    rm -r $RED_DIR/lib/node_modules
fi

#
#   Delete lib files on update
#
if [ -d $RED_DIR/lib ]; then
    rm $RED_DIR/lib/lib*
fi

#
#   Migration to 9.x: remove tools, the package manager and files of previous
#   versions before installing - anything the addon still ships (git) is
#   copied fresh right below, stale leftovers (jq, ffmpeg, the old glibc
#   git-core, ...) must not survive the update
#
for f in git jq jo ffmpeg coap-client pig2vcd pigpiod pigs redmatic-pkg deviceTypes; do
    rm -f $RED_DIR/bin/$f
done
rm -rf $RED_DIR/libexec/git-core $RED_DIR/share/git-core
rm -f $RED_DIR/www/pkg.cgi $RED_DIR/lib/pkg-repo.json
rm -f $RED_DIR/var/do_pkg_upgrade $RED_DIR/var/pkg-upgrade.log $RED_DIR/var/example-flows.json

#
#   Install addon files
#
cp -af redmatic $ADDONS_DIR/

#
#   provides ICU_DATA on armv7l, without which the bundled node does not start
#
. $RED_DIR/versions


#
#   Create default config on first install
#
if [ ! -f $RED_DIR/etc/settings.json ]; then
    mv $RED_DIR/etc/default-settings.json $RED_DIR/etc/settings.json
fi

#
#   Create credentials encryption key
#
if [ ! -f $RED_DIR/etc/credentials.key ]; then
    tr -dc '[:alnum:]' < /dev/urandom  | dd bs=4 count=8 2>/dev/null > $RED_DIR/etc/credentials.key
fi

#
#   Extend extra nodes package.json: keep the user's palette-installed nodes,
#   let versions shipped with the addon (node-red-contrib-ccu) win
#
if [ -f $RED_DIR/var/package.json.old ]; then
    mv $RED_DIR/var/package.json $RED_DIR/var/package.json.new
    $RED_DIR/bin/node -e '
        const fs = require("fs");
        const [oldFile, newFile, outFile] = process.argv.slice(1);
        const oldPkg = JSON.parse(fs.readFileSync(oldFile, "utf8"));
        const newPkg = JSON.parse(fs.readFileSync(newFile, "utf8"));
        const merged = Object.assign({}, oldPkg, newPkg);
        merged.dependencies = Object.assign({}, oldPkg.dependencies, newPkg.dependencies);
        fs.writeFileSync(outFile, JSON.stringify(merged, null, 2) + "\n");
    ' $RED_DIR/var/package.json.old $RED_DIR/var/package.json.new $RED_DIR/var/package.json
    rm $RED_DIR/var/package.json.old $RED_DIR/var/package.json.new
fi

#
#   Remove package-lock
#
if [ -f $RED_DIR/var/package-lock.json ]; then
    rm $RED_DIR/var/package-lock.json
fi

#
#   Create Links
#
rmdir $WWW_DIR 2> /dev/null
# -n: on an update WWW_DIR is already a symlink to a directory, which busybox ln -T refuses to replace
ln -sfn $RED_DIR/www $WWW_DIR
ln -sf $RED_DIR/bin/redmatic $CONF_DIR/rc.d/redmatic
ln -sf $RED_DIR/etc/lighttpd.conf $CONF_DIR/lighttpd/redmatic.conf

#
#   Create Buttons in Homematic WebUI
#
touch $CONF_DIR/hm_addons.cfg
./update_addon redmatic redmatic.cfg

#
#   Link monit configuration
#
if [ -f /usr/bin/monit ]; then
    ln -sf $RED_DIR/etc/monit.cfg /usr/local/etc/monit-redmatic.cfg
    /usr/bin/monit reload
fi

sync

#
#   Start the service again after an update (exit code 0 = no reboot).
#   The original CCU3 firmware installs addons during the SHUTDOWN phase of
#   the reboot that follows the upload: /etc/init.d/S00InstallAddon only
#   implements stop(), which runs /bin/install_addon, which in turn runs this
#   script in a chroot. The following boot sequence starts the addon, so
#   nothing may be started from inside the chroot. OpenCCU runs this script
#   live and does not reboot after an update.
#   Note: this test cannot tell a chroot install from a live run on the CCU3
#   firmware, so a self-update (ROADMAP task 11) has to start the service
#   itself there.
#
if [ $EXITCODE -eq 0 ] && [ ! -f /etc/init.d/S00InstallAddon ]; then
    # never start from the installer's temp dir (OpenCCU deletes it afterwards,
    # spawning npm from a deleted cwd fails: palette editor disabled, #599)
    cd /
    $CONF_DIR/rc.d/redmatic start
fi

exit $EXITCODE
